-- IAC Oracle Database Initialization Script
-- This script creates the basic schema for IAC

-- Note: Oracle DB automatically created via Docker environment variables

-- Create sample tables for testing
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid RAW(16) DEFAULT SYS_GUID() NOT NULL UNIQUE,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('active', 'inactive', 'pending')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_status ON users(status);

-- Create sessions table
CREATE TABLE sessions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR2(64) NOT NULL UNIQUE,
    user_id NUMBER NOT NULL,
    ip_address VARCHAR2(45),
    user_agent CLOB,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_sessions_session_id ON sessions(session_id);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_last_activity ON sessions(last_activity);

-- Create audit log table
CREATE TABLE audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    action VARCHAR2(50) NOT NULL,
    entity_type VARCHAR2(50),
    entity_id VARCHAR2(100),
    changes CLOB,
    ip_address VARCHAR2(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_log_user_id ON audit_log(user_id);
CREATE INDEX idx_audit_log_action ON audit_log(action);
CREATE INDEX idx_audit_log_created_at ON audit_log(created_at);

-- Create sequence for users (if needed)
CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;

-- Create trigger to update updated_at
CREATE OR REPLACE TRIGGER users_update_trigger
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Insert sample data
INSERT INTO users (uuid, username, email, password_hash, first_name, last_name, status) VALUES
(HEXTORAW('550E8400E29B41D4A716446655440000'), 'admin', 'admin@iac.local', '$2a$10$rZfE8qvd1xqY.T9hG3V8H.', 'Admin', 'User', 'active');

INSERT INTO users (uuid, username, email, password_hash, first_name, last_name, status) VALUES
(HEXTORAW('660E8400E29B41D4A716446655440001'), 'testuser', 'test@iac.local', '$2a$10$rZfE8qvd1xqY.T9hG3V8H.', 'Test', 'User', 'active');

COMMIT;

-- Display success message
SELECT 'IAC Oracle database initialized successfully' FROM DUAL;
