package models

import (
	"time"
)

// ThreeDModelFormat represents the format of the 3D model
type ThreeDModelFormat string

const (
	ThreeDModelFormatJSON ThreeDModelFormat = "JSON" // Default Three.js scene format
	ThreeDModelFormatOBJ  ThreeDModelFormat = "OBJ"
	ThreeDModelFormatGLB  ThreeDModelFormat = "GLB"
	ThreeDModelFormatSTL  ThreeDModelFormat = "STL"
	ThreeDModelFormat3DS  ThreeDModelFormat = "3DS"
)

// ThreeDModelStatus represents the workflow status of the 3D model
type ThreeDModelStatus string

const (
	ThreeDModelStatusDraft      ThreeDModelStatus = "DRAFT"       // Initial state, work in progress
	ThreeDModelStatusInProgress ThreeDModelStatus = "IN_PROGRESS" // Actively being worked on
	ThreeDModelStatusReview     ThreeDModelStatus = "REVIEW"      // Ready for review
	ThreeDModelStatusPublished  ThreeDModelStatus = "PUBLISHED"   // Approved and published
	ThreeDModelStatusArchived   ThreeDModelStatus = "ARCHIVED"    // No longer active
)

// ThreeDModelVersion represents a version of a 3D model
type ThreeDModelVersion struct {
	Version            int                    `json:"version" bson:"version"` // Version number (1, 2, 3, etc.)
	IsDefault          bool                   `json:"isDefault" bson:"isDefault"` // True if this is the default version to load
	VersionDescription string                 `json:"versionDescription,omitempty" bson:"versionDescription,omitempty"` // What changed in this version
	ModelData          map[string]interface{} `json:"modelData" bson:"modelData"` // Three.js scene data with all objects
	Format             ThreeDModelFormat      `json:"format" bson:"format"`
	IsAIGenerated      bool                   `json:"isAIGenerated" bson:"isAIGenerated"` // Track if generated by AI
	AIPrompt           string                 `json:"aiPrompt,omitempty" bson:"aiPrompt,omitempty"` // Original AI prompt
	CreatedBy          string                 `json:"createdby" bson:"createdby"`
	CreatedOn          time.Time              `json:"createdon" bson:"createdon"`
}

// ThreeDModel represents a 3D model with version control
// Root properties (Name, Description, Tags, Category, Status) are shared across all versions
// Only ModelData changes between versions
type ThreeDModel struct {
	ID          string `json:"_id" bson:"_id"`
	Name        string `json:"name" bson:"name"` // Root property - same for all versions
	Description string `json:"description,omitempty" bson:"description,omitempty"` // Root property
	Tags        []string `json:"tags,omitempty" bson:"tags,omitempty"` // Root property
	Category    string `json:"category,omitempty" bson:"category,omitempty"` // Root property
	Thumbnail   string `json:"thumbnail,omitempty" bson:"thumbnail,omitempty"` // Root property
	Status      ThreeDModelStatus `json:"status,omitempty" bson:"status,omitempty"` // Workflow status

	// Version Control
	CurrentVersion int                  `json:"currentVersion" bson:"currentVersion"` // Current version number
	Versions       []ThreeDModelVersion `json:"versions" bson:"versions"` // Array of versions

	// Export References (document IDs for exported formats)
	ExportedFormats map[ThreeDModelFormat]string `json:"exportedFormats,omitempty" bson:"exportedFormats,omitempty"`

	// Metadata (calculated from current version)
	ObjectCount int      `json:"objectCount,omitempty" bson:"objectCount,omitempty"` // Number of objects in scene
	Materials   []string `json:"materials,omitempty" bson:"materials,omitempty"` // List of material names used

	// Audit Fields
	CreatedBy       string    `json:"createdby" bson:"createdby"`
	CreatedOn       time.Time `json:"createdon" bson:"createdon"`
	ModifiedBy      string    `json:"modifiedby" bson:"modifiedby"`
	ModifiedOn      time.Time `json:"modifiedon" bson:"modifiedon"`
	RowVersionStamp int       `json:"rowversionstamp" bson:"rowversionstamp"`
}

// ThreeDModelCreateRequest represents the request to create a new 3D model (creates version 1)
type ThreeDModelCreateRequest struct {
	Name          string                 `json:"name" binding:"required"`
	Description   string                 `json:"description,omitempty"`
	Tags          []string               `json:"tags,omitempty"`
	Category      string                 `json:"category,omitempty"`
	ModelData     map[string]interface{} `json:"modelData" binding:"required"` // Three.js scene data
	Format        ThreeDModelFormat      `json:"format"`
	Status        ThreeDModelStatus      `json:"status,omitempty"` // Initial status (defaults to DRAFT)
	IsAIGenerated bool                   `json:"isAIGenerated"`
	AIPrompt      string                 `json:"aiPrompt,omitempty"`
	Thumbnail     string                 `json:"thumbnail,omitempty"`
}

// ThreeDModelUpdateRequest represents the request to update a 3D model
// Can update root properties (name, description, tags, category, status) OR create new version with ModelData
type ThreeDModelUpdateRequest struct {
	Name               string                 `json:"name,omitempty"` // Update root property
	Description        string                 `json:"description,omitempty"` // Update root property
	Tags               []string               `json:"tags,omitempty"` // Update root property
	Category           string                 `json:"category,omitempty"` // Update root property
	Status             ThreeDModelStatus      `json:"status,omitempty"` // Update workflow status
	ModelData          map[string]interface{} `json:"modelData,omitempty"` // If provided, creates new version
	VersionDescription string                 `json:"versionDescription,omitempty"` // For new version
	SetAsDefault       bool                   `json:"setAsDefault,omitempty"` // Set the new version as default
	Thumbnail          string                 `json:"thumbnail,omitempty"` // Update root property
}

// ThreeDModelListResponse represents the response for listing 3D models
type ThreeDModelListResponse struct {
	Data  []ThreeDModel `json:"data"`
	Count int           `json:"count"`
}

// ThreeDModelVersionListResponse represents the response for listing versions
type ThreeDModelVersionListResponse struct {
	ModelID  string               `json:"modelId"`
	Name     string               `json:"name"`
	Versions []ThreeDModelVersion `json:"versions"`
}

// ThreeDModelDocument represents a simplified 3D model structure
// where each version is stored as a separate document
type ThreeDModelDocument struct {
	ID       string `json:"_id" bson:"_id"` // MongoDB ObjectID
	ModelID  string `json:"modelId" bson:"modelId"` // Parent model UUID (same for all versions)
	Version  int    `json:"version" bson:"version"` // Version number (1, 2, 3, etc.)
	IsDefault bool  `json:"isdefault" bson:"isdefault"` // Default version flag

	// Metadata (document-level, can vary per version)
	Name        string   `json:"name" bson:"name"` // Model name
	Description string   `json:"description,omitempty" bson:"description,omitempty"` // Model description
	Category    string   `json:"category,omitempty" bson:"category,omitempty"` // Classification
	Tags        []string `json:"tags,omitempty" bson:"tags,omitempty"` // Search tags

	// Content - simplified to just objects array as user requested
	Objects  []map[string]interface{} `json:"objects" bson:"objects"` // Array of 3D objects
	Metadata map[string]interface{}   `json:"metadata,omitempty" bson:"metadata,omitempty"` // Additional metadata

	// Technical Info
	Format       ThreeDModelFormat `json:"format" bson:"format"` // JSON, OBJ, GLB, STL, 3DS
	ObjectCount  int               `json:"objectCount,omitempty" bson:"objectCount,omitempty"` // Number of 3D objects
	Materials    []string          `json:"materials,omitempty" bson:"materials,omitempty"` // Material names
	Thumbnail    string            `json:"thumbnail,omitempty" bson:"thumbnail,omitempty"` // Preview image

	// AI Generation Tracking
	IsAIGenerated  bool   `json:"isAIGenerated" bson:"isAIGenerated"` // Created by AI?
	AIPrompt       string `json:"aiPrompt,omitempty" bson:"aiPrompt,omitempty"` // Original prompt
	GenerationType string `json:"generationType,omitempty" bson:"generationType,omitempty"` // text-to-3d, image-to-3d, manual, sketch

	// Optional Export References
	ExportedFormats map[ThreeDModelFormat]string `json:"exportedFormats,omitempty" bson:"exportedFormats,omitempty"`

	// Audit Fields
	CreatedBy       string    `json:"createdby" bson:"createdby"`
	CreatedOn       time.Time `json:"createdon" bson:"createdon"`
	ModifiedBy      string    `json:"modifiedby" bson:"modifiedby"`
	ModifiedOn      time.Time `json:"modifiedon" bson:"modifiedon"`
	RowVersionStamp int       `json:"rowversionstamp" bson:"rowversionstamp"`

	// Soft delete
	IsActive bool `json:"isActive" bson:"isActive"` // For soft delete
}

// ThreeDModelDocumentCreateRequest represents the request to create a new 3D model document
type ThreeDModelDocumentCreateRequest struct {
	ModelID        string                   `json:"modelId,omitempty"` // Optional - if provided, creates new version of existing model
	Name           string                   `json:"name" binding:"required"`
	Description    string                   `json:"description,omitempty"`
	Category       string                   `json:"category,omitempty"`
	Tags           []string                 `json:"tags,omitempty"`
	Objects        []map[string]interface{} `json:"objects" binding:"required"` // Array of 3D objects
	Metadata       map[string]interface{}   `json:"metadata,omitempty"`
	Format         ThreeDModelFormat        `json:"format"`
	IsAIGenerated  bool                     `json:"isAIGenerated"`
	AIPrompt       string                   `json:"aiPrompt,omitempty"`
	GenerationType string                   `json:"generationType,omitempty"`
	Thumbnail      string                   `json:"thumbnail,omitempty"`
	IsDefault      bool                     `json:"isdefault"` // Set as default version
}

// ThreeDModelDocumentUpdateRequest represents the request to update a 3D model document
type ThreeDModelDocumentUpdateRequest struct {
	Name        string                   `json:"name,omitempty"`
	Description string                   `json:"description,omitempty"`
	Category    string                   `json:"category,omitempty"`
	Tags        []string                 `json:"tags,omitempty"`
	Objects     []map[string]interface{} `json:"objects,omitempty"`
	Metadata    map[string]interface{}   `json:"metadata,omitempty"`
	Thumbnail   string                   `json:"thumbnail,omitempty"`
	IsDefault   *bool                    `json:"isdefault,omitempty"` // Pointer to distinguish between false and not provided
}

// ThreeDModelDocumentListResponse represents the response for listing 3D model documents
type ThreeDModelDocumentListResponse struct {
	Data  []ThreeDModelDocument `json:"data"`
	Count int                   `json:"count"`
}
